package com.example.a30797.hljunavigationsystem.attractions;

import com.example.a30797.hljunavigationsystem.R;
import com.example.a30797.hljunavigationsystem.schoolgate.MyGraph;

public class Attractions_ifo {
    public static Scenic []Attractions_ifo = {
            new Scenic(R.drawable.nanmen,"南门","威海校区","   南门采用开放式结构，样式简洁，门口东侧立有大理石碑柱，柱身竖写着“山东大学”四个朱红小隶。门前是环海路主干道，门后是宽阔的中心广场。",
                    MyGraph.points[MyGraph.getArrayIndex(0)]),
            new Scenic(R.drawable.yishuxueyuan,"艺术学院（音乐舞蹈楼）","威海校区","    艺术学院设在一栋浅黄色的连体式三层小楼上，造型颇具匠心，东侧的部分形似一架钢琴，颇有艺术美感。从艺术楼里常常流淌出美妙的小提琴曲……",
                    MyGraph.points[MyGraph.getArrayIndex(1)]),
            new Scenic(R.drawable.zhixinghuitang,"知行会堂","威海校区","   知行会堂作为学校最气派的会议厅之一，常常举办大型活动。",
                    MyGraph.points[MyGraph.getArrayIndex(2)]),
            new Scenic(R.drawable.zhixinglou,"知行楼","威海校区","    知行楼是学校的办公楼，是辅导员及校领导办公处。",
                    MyGraph.points[MyGraph.getArrayIndex(3)]),
            new Scenic(R.drawable.haiyangxueyuan,"海洋学院","威海校区","     海洋学院，面水而居，绿树成林。是一栋五层高的白色主建筑。彰显了海洋的博大和宽广。",
                    MyGraph.points[MyGraph.getArrayIndex(4)]),
            new Scenic(R.drawable.shangxueyuan,"商学院","威海校区","    商学院是一座六层高的浅黄色小楼，与海洋学院风格统一，大气明快。是学生上课的主要教学楼之一。",
                    MyGraph.points[MyGraph.getArrayIndex(5)]),
            new Scenic(R.drawable.kuaididian,"外籍专家公寓（威海校区）","威海校区","    菜鸟驿站、妈妈驿站、京东快递以及顺丰快递全部汇集在此处。",
                    MyGraph.points[MyGraph.getArrayIndex(6)]),
            new Scenic(R.drawable.waimai,"外卖点","威海校区","    学生凭借取件码在外卖柜处取外卖。",
                    MyGraph.points[MyGraph.getArrayIndex(7)]),
            new Scenic(R.drawable.yuchi,"浴池","威海校区","    二层为男浴室；三四层为女浴室。旁边有家家悦超市与修钥匙的小摊儿。",
                    MyGraph.points[MyGraph.getArrayIndex(8)]),
            new Scenic(R.drawable.huiyuan,"荟园餐厅","威海校区","    荟园餐厅共两层。著名的厨留香、猪脚饭皆在此处。",
                    MyGraph.points[MyGraph.getArrayIndex(9)]),
            new Scenic(R.drawable.xinyuan,"馨园餐厅","威海校区","    馨园餐厅共四层。其中一到三层为餐厅，四层是文体用品小店集中地。",
                    MyGraph.points[MyGraph.getArrayIndex(10)]),
            new Scenic(R.drawable.taiyuan,"泰园餐厅","威海校区","    泰园餐厅常被人误认为泰国餐厅。其实里面都是地道的中国菜哦~共三层。",
                    MyGraph.points[MyGraph.getArrayIndex(11)]),
            new Scenic(R.drawable.queyuan,"雀园餐厅","威海校区","    雀园餐厅共一层，于2021年翻修完成。",
                    MyGraph.points[MyGraph.getArrayIndex(12)]),
            new Scenic(R.drawable.faxueyuan,"法学院","威海校区","    法学院设有山东大学威海民间法研究所、山东大学威海法律方法论研究所、山东大学威海立法研究所等科研机构。还设有模拟法庭、模拟仲裁实验室、社会工作实验室、社会调查研究中心、诊所式教育中心、学生法律服务中心等实践教学机构。",
                    MyGraph.points[MyGraph.getArrayIndex(13)]),
            new Scenic(R.drawable.tushuguan,"图书馆","威海校区","    创建于 1987 年，2003 年新馆建成使用。新馆大楼主体 12 层，总建筑面积 2 万平方米。 设有阅览座位2000余 个，信息检索点近 1000 个。拥有中外文藏书近 120万册，报刊合订本 3万册，中外文期刊 2400 余种，报纸 130 余种。",
                    MyGraph.points[MyGraph.getArrayIndex(14)]),
            new Scenic(R.drawable.shuxue,"数学与统计学院","威海校区","    山东大学（威海）数学与统计学院在2002年7月成立了数学系，2008年4月改为数学与统计学院。\n  学院致力于培养“宽口径，厚基础，高素质，重创新” 具有较强竞争力、高度责任感和健全人格的应用型数学人才。",
                    MyGraph.points[MyGraph.getArrayIndex(15)]),
            new Scenic(R.drawable.linglongxuetang,"玲珑学堂","威海校区","    玲珑学堂位于图书馆背侧，凭借其优秀的容纳量，成为许多校级活动的举办场所。",
                    MyGraph.points[MyGraph.getArrayIndex(16)]),
            new Scenic(R.drawable.dianzilou,"电子楼（联合理学院）","威海校区","    山东大学澳国立联合理学院，由山东大学和澳大利亚国立大学合作设立。\n  2019年3月21日，经教育部同意设立山东大学澳国立联合理学院，学院隶属于山东大学，为不具有法人资格的中外合作办学机构。",
                    MyGraph.points[MyGraph.getArrayIndex(17)]),
            new Scenic(R.drawable.wenxuelou,"文学楼（文化传播学院）","威海校区","    学院汉语言文学、新闻学、对外汉语三个专业招收本科生，在汉语言文化专业招收留学生，在比较文学与世界文学、中国现当代文学、汉语言文字学、文艺学、中国古代文学和新闻美学五个专业招收硕士研究生，在比较文学与世界文学、中国现当代文学、文艺学专业同时招收博士研究生。",
                    MyGraph.points[MyGraph.getArrayIndex(18)]),
            new Scenic(R.drawable.jidian,"机电与信息工程学院","威海校区","    山东大学（威海）机电与信息工程学院是山东大学（威海）最大的工科学院，下设计算机系、电子系、控制系、机械系及实验教学中心、计算中心等教学机构。",
                    MyGraph.points[MyGraph.getArrayIndex(19)]),
            new Scenic(R.drawable.kexueshiyanlou,"科学实验楼","威海校区","    科学实验楼位于和艺术楼同侧的林荫道上，内部设有许多实验室。山大的学子在这里探知真理，感受科学的魅力。",
                    MyGraph.points[MyGraph.getArrayIndex(20)]),
            new Scenic(R.drawable.wenwailou,"闻外楼（翻译学院、马列部）","威海校区","    翻译学院成立于2004年6月，前身是建立于1991年8月的外国语言文学系，现下设英语系、日语系、翻译系、西语系（西方语言系）、大学英语系、翻译研究所等教学研究机构，翻译研究所在翻译学词典研究方面已经在国内形成优势和特色。",
                    MyGraph.points[MyGraph.getArrayIndex(21)]),
            new Scenic(R.drawable.tianjingchang,"田径场","威海校区","    运动场外围是红蓝相间的塑胶跑道，中心一片阔大的绿茵场，远远望去，像一支彩色的棒棒糖。",
                    MyGraph.points[MyGraph.getArrayIndex(22)]),
            new Scenic(R.drawable.dongbeiya,"东北亚学院","威海校区","    东北亚学院是山东大学（威海）的特色学院，下设朝鲜语、日语、国际政治三个专业。",
                    MyGraph.points[MyGraph.getArrayIndex(23)]),
            new Scenic(R.drawable.tiyuguan,"体育馆","威海校区","    体育馆伫立在田径场东侧，内部设有健身房、乒乓球馆、羽毛球馆、篮球馆、排球馆等体育运动场所。",
                    MyGraph.points[MyGraph.getArrayIndex(24)]),
            new Scenic(R.drawable.youyongguan,"游泳馆","威海校区","    游泳馆位于体育馆的南侧。",
                    MyGraph.points[MyGraph.getArrayIndex(25)]),
            new Scenic(R.drawable.wentianlou,"闻天楼（空间科学与物理学院）","威海校区","      学院下设空间科学系、材料物理系、物理系。学院坐落于最适宜人类居住的美丽海滨城市威海，北拥玛珈山，西濒威海国际海水浴场，自然环境优美、生活设施齐全，工作条件优越。",
                    MyGraph.points[MyGraph.getArrayIndex(26)]),
            new Scenic(R.drawable.wangluolou,"网络楼","威海校区","       网络楼位于电子楼和文学楼中点处，是许多机考考试场所。",
                    MyGraph.points[MyGraph.getArrayIndex(27)]),
            new Scenic(R.drawable.tianwentai,"天文台","威海校区","   山东大学威海天文台（暨威海市天文台）由山东大学、中国科学院国家天文台和威海市联合共建。位于玛珈山顶，分东西两个圆顶。天文台自建成以来，主要开展小行星搜索、超新星巡天、活动星系核光变观测等科研课题。",
                    MyGraph.points[MyGraph.getArrayIndex(28)])
    };
}
